/* ============================================================
   ISSLA Risk — lang.js
   Bilingual support: English (EN) / Spanish (ES)
   ============================================================ */
(function () {
  'use strict';

  /* ----------------------------------------------------------
     TRANSLATIONS
  ---------------------------------------------------------- */
  var T = {
    en: {
      /* --- NAV --- */
      'nav.services': 'Services',
      'nav.about': 'About',
      'nav.faq': 'FAQ',
      'nav.contact': 'Contact',
      'nav.cta': 'Request Briefing',
      /* --- FOOTER --- */
      'footer.tagline': 'Navigating Complex Risks with Actionable Intelligence',
      'footer.disclaimer1': 'Intelligence services provided do not constitute legal, regulatory, or compliance counsel.',
      'footer.disclaimer2': 'ISSLA Risk is a corporate intelligence consulting and advisory firm. We do not operate as a licensed private investigation agency.',
      'footer.col.services': 'Services',
      'footer.link.dd': 'Due Diligence',
      'footer.link.bg': 'Background Analysis',
      'footer.link.rep': 'Reputation Analysis',
      'footer.link.cr': 'Country Risk',
      'footer.col.company': 'Company',
      'footer.link.about': 'About',
      'footer.link.faq': 'FAQ',
      'footer.link.contact': 'Contact',
      'footer.col.follow': 'Follow',
      'footer.col.legal': 'Legal',
      'footer.link.privacy': 'Privacy Policy',
      'footer.link.cookie': 'Cookie Policy',
      'footer.link.terms': 'Terms and Conditions',
      'footer.link.ethics': 'Code of Ethics',
      'footer.copyright': '© 2025 ISSLA Risk Global Services LLC. All rights reserved.',
      'footer.offices': 'Offices: United States · Panama',
      'footer.confidentiality': 'This site and its contents are strictly confidential.',
      'footer.privacy': 'Privacy Policy',
      /* --- COOKIE BANNER --- */
      'cookie.text': 'We use cookies to improve your experience.',
      'cookie.accept': 'Accept',
      'cookie.decline': 'Decline',
      /* --- INDEX — NEW CONVERSION-FOCUSED --- */
      /* Hero */
      'home.hero.eyebrow': 'ISSLA Risk — Corporate Intelligence',
      'home.hero.h1': 'Know exactly who you are doing business with — before it\u2019s too late.',
      'home.hero.sub': 'Open-source intelligence reports on individuals and companies in 48\u201372 hours.',
      'home.hero.cta': 'Request report now',
      /* Pilares */
      'home.pillar1.title': 'What the EDD report includes',
      'home.pillar1.li1': 'Complete background check',
      'home.pillar1.li2': 'Litigation and legal exposure',
      'home.pillar1.li3': 'Identified assets',
      'home.pillar1.li4': 'Corporate networks',
      'home.pillar1.li5': 'Reputational risk',
      'home.pillar2.title': 'Delivery time',
      'home.pillar2.text': 'Delivery in 48\u201372 business hours from payment confirmation. Confidential PDF format with risk classification.',
      'home.pillar3.title': 'Guaranteed confidentiality',
      'home.pillar3.text': 'NDA from first contact. Non-attributable methodology. Your data and the subject\u2019s information remain protected at all times.',
      /* Audience */
      'home.audience.title': 'Who is this for?',
      'home.audience.lawyers': 'Litigation lawyers',
      'home.audience.lawyers.desc': 'Verify opposing parties, witnesses, and interested parties before procedural strategies.',
      'home.audience.ma': 'M&A due diligence teams',
      'home.audience.ma.desc': 'Verified EDD reports for investment committees and merger & acquisition processes.',
      'home.audience.investors': 'Private investors',
      'home.audience.investors.desc': 'Know your potential investment partners before committing capital.',
      'home.audience.compliance': 'Compliance officers',
      'home.audience.compliance.desc': 'AML/KYC compliance with verifiable and defensible intelligence for regulators.',
      /* Authority */
      'home.authority.title': 'Verified methodology',
      'home.authority.desc': 'We combine three intelligence streams for each report:',
      'home.authority.osint': 'Official records, court archives, corporate registries and verified public sources.',
      'home.authority.humint': 'Primary source networks on the ground for confirmation of business activity and reputation.',
      'home.authority.socmin': 'Analysis of patterns in professional networks and digital behavior.',
      'home.authority.jurisdictions.title': 'Covered jurisdictions',
      'home.authority.deliverable.title': 'Deliverable format',
      'home.authority.deliverable.format': 'Format',
      'home.authority.deliverable.formatval': 'Confidential PDF',
      'home.authority.deliverable.classification': 'Classification',
      'home.authority.deliverable.classval': 'Risk Level',
      'home.authority.deliverable.sources': 'Sources',
      'home.authority.deliverable.sourcesval': 'Verified and cited',
      /* Pricing */
      'home.pricing.title': 'EDD Reports — Available options',
      'home.pricing.sub': 'Each report includes executive summary, verified findings, and risk classification.',
      'home.pricing.cta': 'Order this report',
      'home.pricing.basic.tier': 'Basic',
      'home.pricing.basic.name': 'EDD Standard',
      'home.pricing.basic.desc': 'Public records, judicial background, basic corporate structure and sanctions screening.',
      'home.pricing.basic.f1': 'Personal background',
      'home.pricing.basic.f2': 'Litigation and proceedings',
      'home.pricing.basic.f3': 'AML/KYC screening',
      'home.pricing.basic.f4': 'Basic corporate structure',
      'home.pricing.basic.delivery': 'Delivery: 48\u201372 hours',
      'home.pricing.adv.badge': 'Recommended',
      'home.pricing.adv.tier': 'Advanced',
      'home.pricing.adv.name': 'EDD Comprehensive',
      'home.pricing.adv.desc': 'Complete background analysis, assets, corporate networks, human sources and reputational risk.',
      'home.pricing.adv.f1': 'Everything in Basic level',
      'home.pricing.adv.f2': 'Identified assets',
      'home.pricing.adv.f3': 'Complete corporate networks',
      'home.pricing.adv.f4': 'HUMINT + SOCMIN',
      'home.pricing.adv.f5': 'Reputational risk analysis',
      'home.pricing.adv.delivery': 'Delivery: 48\u201372 hours',
      'home.pricing.exec.tier': 'Executive',
      'home.pricing.exec.name': 'EDD Executive',
      'home.pricing.exec.desc': 'Maximum depth report for critical decisions. Includes executive briefing with senior analyst.',
      'home.pricing.exec.f1': 'Everything in Advanced level',
      'home.pricing.exec.f2': 'Deep financial dive',
      'home.pricing.exec.f3': 'Senior analyst briefing',
      'home.pricing.exec.f4': '30-day follow-up',
      'home.pricing.exec.delivery': 'Delivery: 5\u20137 business days',
      /* Payment */
      'home.payment.title': 'How to start your investigation',
      'home.payment.step1.title': 'Complete the form',
      'home.payment.step1.desc': 'Enter the subject\u2019s data: name, country/jurisdiction and any relevant additional information.',
      'home.payment.step2.title': 'Make the transfer',
      'home.payment.step2.desc': 'Transfer to the account number below. Use your name as reference.',
      'home.payment.bank.name': 'Bank',
      'home.payment.bank.account': 'Account',
      'home.payment.bank.routing': 'Routing',
      'home.payment.bank.swift': 'SWIFT',
      'home.payment.reveal': 'Reveal bank details',
      'home.payment.step3.title': 'Receive your report',
      'home.payment.step3.desc': 'We confirm your payment and send the EDD report in 48\u201372 business hours in confidential PDF format.',
      'home.payment.form.name': 'Requester name *',
      'home.payment.form.name.ph': 'Your full name',
      'home.payment.form.email': 'Email *',
      'home.payment.form.email.ph': 'your@email.com',
      'home.payment.form.subject': 'Subject name to investigate *',
      'home.payment.form.subject.ph': 'Full name or company name',
      'home.payment.form.country': 'Country / Jurisdiction *',
      'home.payment.form.country.ph': 'Select jurisdiction',
      'home.payment.form.tier': 'Report type',
      'home.payment.form.tierbasic': 'EDD Standard (Basic)',
      'home.payment.form.tieradv': 'EDD Comprehensive (Advanced)',
      'home.payment.form.tierexec': 'EDD Executive',
      'home.payment.form.message': 'Additional information (optional)',
      'home.payment.form.message.ph': 'Any additional information that may help with the investigation...',
      'home.payment.form.submit': 'Submit request and confirm payment',
      'home.payment.form.confidential': 'All information provided is strictly confidential and will only be used to generate the requested report.',
      'home.payment.success.title': 'Request received',
      'home.payment.success.text': 'We will contact you within 24 business hours to confirm details and proceed with the delivery of your report.',
      /* --- SERVICES --- */
      'svc.hero.eyebrow': 'Our Services',
      'svc.hero.title': 'Corporate Intelligence &amp; Enhanced Due Diligence',
      'svc.hero.sub': 'Pre-transaction intelligence, KYC, reputational analysis, and jurisdictional risk — each calibrated to your mandate. Defensible before regulators and courts.',
      'svc.s1.eyebrow': 'Service 01',
      'svc.s1.title': 'Enhanced Due Diligence',
      'svc.s1.body1': 'Global Due Diligence is our most comprehensive service, designed for M&A transactions, joint ventures, high-value counterparty relationships, and critical hiring decisions. We go beyond database searches to surface the information that defines whether a deal, partnership, or appointment carries hidden risk.',
      'svc.s1.body2': 'Our due diligence engagements cover corporate structure and beneficial ownership, financial history and litigation exposure, regulatory sanctions and AML/KYC compliance, corporate property mapping, and UBO identification — delivered in tiered report formats calibrated to your risk exposure and decision timeline.',
      'svc.s1.included': "What's Included",
      'svc.s1.li1': 'Corporate structure & beneficial ownership',
      'svc.s1.li2': 'Litigation history and legal exposure',
      'svc.s1.li3': 'Regulatory and sanctions screening (AML/KYC/OFAC)',
      'svc.s1.li4': 'Financial background analysis',
      'svc.s1.li5': 'UBO identification',
      'svc.s1.li6': 'Multi-jurisdictional coverage',
      'svc.s1.tiers.header': 'Report Tiers',
      'svc.s1.tier.basic.key': 'Basic',
      'svc.s1.tier.basic.val': 'Core records, public sources · 5–10 days',
      'svc.s1.tier.int.key': 'Intermediate',
      'svc.s1.tier.int.val': 'Extended OSINT + source inquiry · 10–18 days',
      'svc.s1.tier.adv.key': 'Advanced',
      'svc.s1.tier.adv.val': 'Full HUMINT + field source consultation · 15–25 days',
      'svc.s1.tiers.footer': 'All tiers include executive summary + risk assessment',
      'svc.s1.bestfor': 'Best For',
      'svc.s2.eyebrow': 'Service 02',
      'svc.s2.title': 'KYC / Customer Due Diligence',
      'svc.s2.body1': 'Background Analysis is a focused intelligence engagement designed for specific individuals or entities where a full due diligence scope is not warranted. It is the preferred service for executive vetting, board-level appointments, key hire evaluations, and preliminary pre-engagement screening.',
      'svc.s2.body2': 'We apply open-source intelligence methodology to build a verified profile of the subject — drawing on corporate registries, court records, media archives, professional networks, and sector-specific databases — and identify flags that conventional HR or legal review would not surface.',
      'svc.s2.included': "What's Included",
      'svc.s2.li1': 'Corporate registry and directorship mapping',
      'svc.s2.li2': 'Court records and litigation history',
      'svc.s2.li3': 'Media archive review and adverse flag identification',
      'svc.s2.li4': 'Professional network and association analysis',
      'svc.s2.li5': 'Sector-specific database screening',
      'svc.s2.li6': 'Summary risk assessment with confidence ratings',
      'svc.s2.bestfor': 'Best For',
      'svc.s2.eng.header': 'Engagement Details',
      'svc.s2.eng.deliv.key': 'Delivery',
      'svc.s2.eng.deliv.val': '5–10 business days',
      'svc.s2.eng.lang.key': 'Languages',
      'svc.s2.eng.lang.val': 'English and Spanish',
      'svc.s2.eng.scope.key': 'Scope',
      'svc.s2.eng.scope.val': 'Individual or entity',
      'svc.s2.eng.footer': 'Available as standalone or as pre-qualification for full due diligence',
      'svc.s3.eyebrow': 'Service 03',
      'svc.s3.title': 'Reputational Intelligence',
      'svc.s3.body1': 'Reputation Analysis is an intelligence product focused on the public and non-public narrative surrounding a person, entity, or brand. It is designed for clients who need to understand how a subject is perceived — across media, professional networks, sector channels, and open-source environments — before entering a relationship with them.',
      'svc.s3.body2': "We identify reputation risk vectors: adverse media patterns, controversy associations, network-level risks, and discrepancies between a subject's stated and observed profile. The deliverable is a calibrated risk assessment, not a media summary.",
      'svc.s3.included': "What's Included",
      'svc.s3.li1': 'Adverse media pattern identification',
      'svc.s3.li2': 'Controversy and association risk mapping',
      'svc.s3.li3': 'Stated vs. observed profile discrepancy analysis',
      'svc.s3.li4': 'Network-level exposure assessment',
      'svc.s3.li5': 'Digital and social media footprint review',
      'svc.s3.li6': 'Calibrated risk rating with sourced findings',
      'svc.s3.what.header': 'What It Surfaces',
      'svc.s3.adv.key': 'Adverse Media',
      'svc.s3.adv.val': 'Pattern-based, not keyword-based',
      'svc.s3.cont.key': 'Controversy',
      'svc.s3.cont.val': 'Historical and emerging associations',
      'svc.s3.disc.key': 'Discrepancies',
      'svc.s3.disc.val': 'Stated vs. observed profile gaps',
      'svc.s3.net.key': 'Network Risk',
      'svc.s3.net.val': 'Indirect exposures via associations',
      'svc.s3.dig.key': 'Digital Footprint',
      'svc.s3.dig.val': 'Online presence and signal mapping',
      'svc.s3.footer': 'Deliverable: calibrated risk assessment with source documentation',
      'svc.s3.bestfor': 'Best For',
      'svc.s4.eyebrow': 'Service 04',
      'svc.s4.title': 'Jurisdictional Risk Assessment',
      'svc.s4.body1': 'Our Country Risk assessments deliver a structured analysis of the political, regulatory, security, and operational environment in a target jurisdiction. They are designed for organizations planning market entry, asset protection strategies, or operational continuity planning in complex or high-risk environments.',
      'svc.s4.body2': 'Coverage is deepest in Latin America, the Caribbean, and the Middle East — markets where political volatility, regulatory opacity, and ESG factors combine to create risks that standard market research does not capture.',
      'svc.s4.included': "What's Included",
      'svc.s4.li1': 'Risk rating framework by domain',
      'svc.s4.li2': 'Political scenario analysis and forecasting',
      'svc.s4.li3': 'Regulatory and compliance overview',
      'svc.s4.li4': 'ESG risk factors and exposure mapping',
      'svc.s4.li5': 'Security environment assessment',
      'svc.s4.li6': 'Operational recommendations',
      'svc.s4.deliv.header': 'Deliverables',
      'svc.s4.risk.key': 'Risk Framework',
      'svc.s4.risk.val': 'Multi-domain risk rating matrix',
      'svc.s4.pol.key': 'Political',
      'svc.s4.pol.val': 'Scenario analysis and probability forecast',
      'svc.s4.reg.key': 'Regulatory',
      'svc.s4.reg.val': 'Compliance landscape overview',
      'svc.s4.esg.key': 'ESG',
      'svc.s4.esg.val': 'Environmental, social, governance risk factors',
      'svc.s4.op.key': 'Operational',
      'svc.s4.op.val': 'Actionable recommendations by scenario',
      'svc.s4.footer': 'Engagements include an executive briefing call upon delivery',
      'svc.s4.coverage': 'Coverage',
      'svc.rep.eyebrow': 'Deliverables',
      'svc.rep.title': 'Defensible Intelligence. Decisive Delivery.',
      'svc.rep.sub': 'All reports open with an executive summary and risk assessment, followed by detailed findings organized by intelligence domain. Built to withstand scrutiny before regulators, courts, and investment committees.',
      'svc.rep.basic.num': 'Basic',
      'svc.rep.basic.name': 'Foundation Report',
      'svc.rep.basic.desc': 'Core records and public-source findings. Executive summary, key risk flags, confidence ratings. Delivered in 5–10 business days.',
      'svc.rep.int.num': 'Intermediate',
      'svc.rep.int.name': 'Standard Report',
      'svc.rep.int.desc': 'Extended OSINT plus source inquiry. Full findings by domain with source attribution. Delivered in 10–18 business days.',
      'svc.rep.adv.num': 'Advanced',
      'svc.rep.adv.name': 'Full Intelligence Report',
      'svc.rep.adv.desc': 'Complete HUMINT and field source consultation. Comprehensive domain analysis with all confidence and source documentation. 15–25 business days.',
      'svc.rep.sample': 'A redacted sample report is available upon request · info@isslarisk.com',
      'svc.cta.title': 'Start Your Due Diligence',
      'svc.cta.sub': "Submit a mandate and we'll scope the right service within 48 hours. 48-hour response guaranteed.",
      'svc.cta.btn': 'Submit a Mandate',
      'svc.included.label': "What's Included",
      'svc.bestfor.label': 'Best For',
      'svc.s1.bullets': '<li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Corporate structure &amp; beneficial ownership</li>\n            <li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Litigation history and legal exposure</li>\n            <li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Regulatory and sanctions screening (AML/KYC/OFAC)</li>\n            <li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Financial background analysis</li>\n            <li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> UBO identification</li>\n            <li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Multi-jurisdictional coverage</li>',
      'svc.s2.bullets': '<li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Corporate registry and directorship mapping</li>\n            <li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Court records and litigation history</li>\n            <li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Media archive review and adverse flag identification</li>\n            <li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Professional network and association analysis</li>\n            <li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Sector-specific database screening</li>\n            <li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Summary risk assessment with confidence ratings</li>',
      'svc.s3.bullets': '<li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Adverse media pattern identification</li>\n            <li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Controversy and association risk mapping</li>\n            <li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Stated vs. observed profile discrepancy analysis</li>\n            <li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Network-level exposure assessment</li>\n            <li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Digital and social media footprint review</li>\n            <li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Calibrated risk rating with sourced findings</li>',
      'svc.s4.bullets': '<li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Risk rating framework by domain</li>\n            <li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Political scenario analysis and forecasting</li>\n            <li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Regulatory and compliance overview</li>\n            <li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> ESG risk factors and exposure mapping</li>\n            <li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Security environment assessment</li>\n            <li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Operational recommendations</li>',
      /* --- ABOUT --- */
      'about.hero.eyebrow': 'About the Firm',
      'about.hero.title': 'Strategic Due Diligence · Transaction Intelligence · Cross-Border Risk',
      'about.hero.sub': '17 years. 1,200+ mandates. On-the-ground coverage where others rely on databases. Intelligence before capital deployment.',
      'about.who.eyebrow': 'Who We Are',
      'about.who.title': 'Corporate Intelligence for High-Stakes Decisions',
      'about.who.body1': 'ISSLA Risk is a specialist corporate intelligence and risk advisory firm. We serve multinational corporations, private equity funds, legal practices, family offices, and government-adjacent entities that require verified intelligence before committing capital, entering partnerships, or expanding into complex markets.',
      'about.who.body2': 'Our analysts combine open-source intelligence, human source networks, and proprietary research methodologies to produce reports that are not merely informative — they are actionable. Every engagement is treated with absolute discretion, and every finding is sourced, verified, and professionally presented.',
      'about.who.body3': 'We operate across the Americas, Europe, the Middle East, and North Africa, with specialist depth in Latin American and Caribbean markets that sets us apart from generalist consultancies.',
      'about.stat.engagements': 'Mandates Completed',
      'about.stat.countries': 'Countries Covered',
      'about.stat.confidential': 'Years of Operation',
      'about.dossier.header': 'FIRM PROFILE',
      'about.dossier.confidential': 'CONFIDENTIAL',
      'about.dossier.founded.key': 'Founded',
      'about.dossier.entity.key': 'Entity',
      'about.dossier.category.key': 'Category',
      'about.dossier.hq.key': 'Headquarters',
      'about.dossier.regional.key': 'Regional Office',
      'about.dossier.coverage.key': 'Coverage',
      'about.dossier.coverage.val': 'North America · Caribbean · South America',
      'about.dossier.languages.key': 'Languages',
      'about.dossier.mandate.key': 'Mandate',
      'about.dossier.mandate.val': 'Verified intelligence. Zero tolerance for unverified claims.',
      'about.dossier.ethics.key': 'Ethics',
      'about.dossier.ethics.val': 'Full GDPR & Privacy Act compliance',
      'about.method.eyebrow': 'How We Work',
      'about.method.title': 'A Methodology Built on Verification',
      'about.method.sub': 'Every ISSLA Risk engagement follows a structured three-phase intelligence cycle — ensuring that every conclusion in your report can withstand professional scrutiny.',
      'about.method.1.name': 'OSINT — Open Source Intelligence',
      'about.method.1.tag': 'Intelligence Layer 01',
      'about.method.1.desc': "We begin with a structured open-source sweep: corporate registries, court records, regulatory filings, sanctions databases, adverse media archives, and official government sources. This phase builds the foundational data layer for every engagement and establishes a baseline timeline of the subject's activities.",
      'about.method.2.name': 'HUMINT — Human Intelligence',
      'about.method.2.tag': 'Intelligence Layer 02',
      'about.method.2.desc': 'Where documents end, people begin. Our regional source networks provide ground-level verification that no database can replicate: confirmation of business activity, reputational standing among peers, behavioral patterns, and relationships that formal records never capture. All HUMINT is handled under strict operational security protocols.',
      'about.method.3.name': 'SOCMIN — Social Media Intelligence',
      'about.method.3.tag': 'Intelligence Layer 03',
      'about.method.3.desc': 'Digital footprints reveal what formal sources conceal. ISSLA Risk analysts conduct structured analysis of professional and social media profiles, public statements, network affiliations, and online behavioral patterns. This layer is particularly valuable for identifying inconsistencies between stated positions and observed conduct.',
      'about.cap.eyebrow': 'Core Capabilities',
      'about.cap.title': 'What Sets ISSLA Risk Apart',
      'about.cap.1.title': 'Regional Depth',
      'about.cap.1.desc': 'Specialist expertise in Latin American and Caribbean markets — jurisdictions where informal networks, political dynamics, and opacity of records demand analysts with genuine on-the-ground knowledge, not just database access.',
      'about.cap.2.title': 'Multi-Layer Verification',
      'about.cap.2.desc': 'No finding reaches your report without independent corroboration. Every significant claim is verified across at least two independent sources — eliminating the rumor-as-fact problem that plagues lesser intelligence products.',
      'about.cap.3.title': 'Legal & Compliance Integration',
      'about.cap.3.desc': 'Our analysts understand how reports will be used — in investment committee presentations, legal proceedings, regulatory filings, and board-level decisions. Reports are structured to meet the evidentiary standards of your specific use case.',
      'about.cap.4.title': 'Absolute Discretion',
      'about.cap.4.desc': 'Every engagement is confidential by default. We do not confirm or deny client relationships, we do not use client information for any purpose beyond the specific engagement, and all deliverables are transmitted through secure channels.',
      'about.sectors.eyebrow': 'Industries Served',
      'about.sectors.title': 'Trusted Across Sectors',
      'about.sectors.sub': 'Any organization whose decisions carry significant financial, legal, or reputational consequences benefits from verified intelligence.',
      'about.sector.pe': 'Private Equity & Venture Capital',
      'about.sector.corp': 'Multinational Corporations',
      'about.sector.legal': 'Legal & Law Firms',
      'about.sector.fo': 'Family Offices',
      'about.sector.fi': 'Financial Institutions',
      'about.sector.ins': 'Insurance & Reinsurance',
      'about.sector.re': 'Real Estate & Development',
      'about.sector.gov': 'Government-Adjacent Entities',
      'about.sector.energy': 'Energy & Natural Resources',
      'about.sector.pharma': 'Pharmaceutical & Healthcare',
      'about.sector.infra': 'Infrastructure & Construction',
      'about.sector.tech': 'Technology & Telecom',
      'about.cov.eyebrow': 'Geographic Coverage',
      'about.cov.title': 'Where We Operate',
      'about.cov.sub': 'ISSLA Risk covers North America, the Caribbean, and South America — with specialist depth in the markets where opacity, political risk, and jurisdictional complexity are highest.',
      'about.cov.na.title': 'North America',
      'about.cov.na.desc': 'Full coverage of the United States and Canada, including cross-border corporate analyses, regulatory compliance research, and pre-transaction partner vetting across all major jurisdictions.',
      'about.cov.carib.title': 'The Caribbean',
      'about.cov.carib.desc': 'Specialist depth across Caribbean offshore jurisdictions, island-state corporate registries, and regional financial centers — where beneficial ownership opacity and shell structure complexity demand experienced local knowledge.',
      'about.cov.sa.title': 'South America',
      'about.cov.sa.desc': 'Comprehensive coverage across South American markets, with particular expertise in Colombia, Brazil, Argentina, and Peru — jurisdictions with high-value investment activity alongside elevated political and regulatory risk.',
      'about.off.eyebrow': 'Our Offices',
      'about.off.title': 'Two Strategic Locations',
      'about.off.1.flag': 'Americas — Headquarters',
      'about.off.1.hours': 'Mon – Fri, 09:00 – 18:00 GMT-3',
      'about.off.2.flag': 'Latin America — Regional Office',
      'about.off.2.hours': 'Mon – Fri, 09:00 – 17:00 GMT-3',
      'about.off.2.ops': 'Latin America & Caribbean intelligence operations',
      'about.cta.title': 'Start Your Due Diligence',
      'about.cta.sub': 'Contact our team to discuss your specific intelligence requirements. All inquiries are treated with absolute confidentiality.',
      'about.cta.btn1': 'Request a Briefing',
      'about.cta.btn2': 'View Our Services',
      /* --- FAQ --- */
      'faq.hero.eyebrow': 'Frequently Asked Questions',
      'faq.hero.title': 'Questions & Answers',
      'faq.hero.sub': "Everything you need to know about ISSLA Risk's services, process, and how we work. If your question isn't answered here, contact us directly.",
      'faq.cat.about': 'About ISSLA Risk',
      'faq.cat.services': 'Our Services',
      'faq.cat.process': 'Process & Methodology',
      'faq.cat.confidentiality': 'Confidentiality & Security',
      'faq.cat.reports': 'Reports & Deliverables',
      'faq.cat.engagement': 'Starting an Engagement',
      'faq.sidebar.still': 'Still have questions?',
      'faq.sidebar.contact': 'Contact Us',
      'faq.a1.q': 'What is ISSLA Risk?',
      'faq.a1.a': '<p>ISSLA Risk is a specialist corporate intelligence and risk advisory firm. We provide verified intelligence products to multinational corporations, private equity funds, legal practices, family offices, and government-adjacent entities. Our work focuses on four disciplines: global due diligence, background analysis, reputation analysis, and country risk &amp; political forecasting.</p>',
      'faq.a2.q': 'Where is ISSLA Risk based?',
      'faq.a2.a': '<p>Our headquarters is located in Albuquerque, New Mexico, USA. We also operate a regional office in Panama City, Republic of Panama, which supports our Latin American and Caribbean intelligence operations. Both offices can be reached at info@isslarisk.com.</p>',
      'faq.a3.q': 'What geographic regions does ISSLA Risk cover?',
      'faq.a3.a': '<p>ISSLA Risk covers North America, the Caribbean, and South America. We have particular expertise in markets characterized by elevated opacity, political risk, or complex regulatory environments — including the United States, Canada, Panama, Colombia, Brazil, Argentina, Peru, Mexico, and Caribbean offshore jurisdictions such as the BVI and Cayman Islands. Founded in 2009, we have built specialized source networks across these regions over more than fifteen years of operational activity.</p>',
      'faq.s1.q': 'What services does ISSLA Risk offer?',
      'faq.s1.a': '<p>We offer four core intelligence services:</p><ul><li><strong>Global Due Diligence</strong> — Pre-investment partner and vendor vetting, available in three tiers (Essential, Comprehensive, and Executive).</li><li><strong>Background Analysis</strong> — Deep professional history and public record research on individuals for high-stakes appointments or partnerships.</li><li><strong>Reputation Analysis</strong> — Structured assessment of how a subject entity or individual is perceived across markets, media, and stakeholder networks.</li><li><strong>Country Risk &amp; Political Forecast</strong> — Geopolitical and regulatory risk assessments for market entry, operational decisions, or investment committees.</li></ul>',
      'faq.s2.q': 'Who are your typical clients?',
      'faq.s2.a': '<p>Our clients include multinational corporations, private equity and venture capital funds, legal and law firms, family offices, financial institutions, insurance and reinsurance companies, real estate developers, energy companies, and government-adjacent entities. Our common thread is clients whose decisions carry significant financial, legal, or reputational consequences — and who require verified intelligence rather than speculation.</p>',
      'faq.s3.q': 'Can ISSLA Risk conduct background research on individuals?',
      'faq.s3.a': '<p>Yes — background analysis on individuals is one of our core services, conducted as open-source and public record research within the scope of our corporate intelligence consulting mandate. All research is performed using lawful methods: public registries, court records, media archives, professional networks, and human source consultation. We research professional history, regulatory standing, litigation records, financial conduct, and reputational profile. ISSLA Risk is a corporate intelligence consulting and advisory firm — we do not operate as a licensed private investigation agency, and we do not conduct surveillance, covert physical tracking, or any activity that falls outside the bounds of applicable law.</p>',
      'faq.p1.q': 'What methodology does ISSLA Risk use?',
      'faq.p1.a': '<p>Our methodology is built on three intelligence layers: OSINT (Open Source Intelligence), HUMINT (Human Intelligence), and SOCMIN (Social Media Intelligence). OSINT covers structured research of public records, registries, filings, and media archives. HUMINT involves our regional source networks providing ground-level verification. SOCMIN analyses digital footprints, professional profiles, and online behavioral patterns. Every significant finding requires independent corroboration before it appears in your report.</p>',
      'faq.p2.q': 'How long does an engagement take?',
      'faq.p2.a': '<p>Turnaround depends on the scope and type of engagement. An Essential due diligence report typically delivers within 5–7 business days. Comprehensive reports generally require 10–15 business days. Executive-level mandates, multi-subject engagements, and country risk assessments are scoped and scheduled individually. We can discuss expedited delivery for time-sensitive situations — contact us to discuss your specific timeline.</p>',
      'faq.p3.q': 'How does ISSLA Risk verify its findings?',
      'faq.p3.a': '<p>No finding reaches your report without independent corroboration. We apply a two-source minimum standard for every significant claim — meaning every substantive conclusion is verified through at least two independent, non-derivative sources. Where a claim cannot be independently verified, it is either excluded or clearly labeled as unverified and attributed to its single source. This standard is non-negotiable across all engagement tiers.</p>',
      'faq.c1.q': 'How does ISSLA Risk protect client confidentiality?',
      'faq.c1.a': '<p>Client confidentiality is the foundation of our practice. We do not confirm or deny the existence of any client relationship. All engagement details, deliverables, and communications are treated as strictly confidential. We do not use client information for any secondary purpose, do not discuss mandates with third parties, and do not reference past clients in marketing materials without explicit written authorization. All staff operate under binding confidentiality agreements.</p>',
      'faq.c2.q': 'Is ISSLA Risk compliant with GDPR and data protection laws?',
      'faq.c2.a': '<p>Yes. ISSLA Risk operates in full compliance with the European General Data Protection Regulation (GDPR), the United States Privacy Act, and applicable local data protection regulations in each jurisdiction where we operate. All research is conducted using lawful bases, and personal data is processed strictly for the purpose of the specific engagement. For full details, please review our <a href="privacy-policy.html">Privacy Policy</a>.</p>',
      'faq.c3.q': 'How are reports and communications transmitted?',
      'faq.c3.a': '<p>All deliverables are transmitted through secure, encrypted channels. We do not transmit sensitive reports via unencrypted email as standard practice. Specific secure delivery arrangements are confirmed with each client at the outset of the engagement. If you have existing secure communication protocols you prefer, we can adapt to them.</p>',
      'faq.r1.q': 'What does an ISSLA Risk report contain?',
      'faq.r1.a': '<p>Report structure varies by service type and tier, but all ISSLA Risk reports include: an executive summary designed for decision-maker consumption, detailed findings organized by risk category, source attribution for every substantive claim, a risk rating or assessment conclusion, and actionable recommendations. Reports are professionally formatted and designed to be presented directly to investment committees, legal counsel, or boards without editorial modification.</p>',
      'faq.r2.q': 'What are the differences between the Essential, Comprehensive, and Executive tiers?',
      'faq.r2.a': '<p><strong>Essential:</strong> Covers sanctions &amp; watchlist screening, adverse media review, corporate registry verification, litigation records, and a preliminary risk summary. Suitable for initial screening before deeper engagement. Delivery: 5–7 business days.</p><p><strong>Comprehensive:</strong> Adds professional history verification, financial conduct analysis, reputational intelligence from human sources, network mapping, and a detailed risk narrative. Suitable for pre-investment or pre-appointment mandates. Delivery: 10–15 business days.</p><p><strong>Executive:</strong> A full-spectrum engagement including all Comprehensive elements plus deep financial history, beneficial ownership tracing, extended HUMINT deployment, litigation strategy analysis, and a senior analyst briefing. Bespoke scope and timeline.</p>',
      'faq.r3.q': 'Can ISSLA Risk provide ongoing monitoring rather than a one-time report?',
      'faq.r3.a': '<p>Yes. For clients who require continuous visibility on a subject, jurisdiction, or market, we offer retainer-based monitoring arrangements. These are structured individually based on the scope of monitoring required. Contact us to discuss ongoing monitoring requirements.</p>',
      'faq.e1.q': 'How do I initiate an engagement with ISSLA Risk?',
      'faq.e1.a': '<p>The simplest way to begin is via our <a href="contact.html">contact form</a> or by emailing info@isslarisk.com. We will respond within one business day to schedule a confidential briefing call. During that call, we define scope, timeline, deliverables, and commercial terms. No sensitive details about the subject of the engagement are required at the inquiry stage — we only need to understand the broad nature of the mandate to provide an initial assessment.</p>',
      'faq.e2.q': 'What information do I need to provide to start?',
      'faq.e2.a': '<p>At the outset of an engagement, we require: the identity of the subject (individual or entity), the jurisdiction(s) of primary interest, the purpose of the engagement (investment, compliance, litigation support, etc.), and any specific risk concerns you want prioritized. The more context you provide, the better we can tailor the engagement. Supplementary documents — corporate filings, prior reports, correspondence — are always welcome and treated as strictly confidential.</p>',
      'faq.e3.q': 'Does ISSLA Risk work with clients outside the United States?',
      'faq.e3.a': '<p>Absolutely. ISSLA Risk serves clients globally regardless of where they are headquartered. Our Panama City office supports Latin American and Caribbean clients, while our Albuquerque headquarters serves North American mandates. We work with organizations based anywhere in the world that need intelligence coverage within our operating regions. Engagements are conducted in English, Spanish, and Portuguese. Communications and deliverables can be provided in the client\'s preferred language.</p>',
      'faq.cta.title': "Didn't Find Your Answer?",
      'faq.cta.sub': 'Contact our team directly. All inquiries are treated with complete confidentiality and answered within one business day.',
      'faq.cta.btn1': 'Contact Us',
      'faq.cta.btn2': 'View Our Services',
      /* --- CONTACT --- */
      'contact.hero.eyebrow': 'Begin an Engagement',
      'contact.hero.title': 'Request a Confidential Consultation',
      'contact.hero.sub': 'Submit a mandate or start a conversation. 48-hour response guaranteed. All inquiries are confidential — no commitment required.',
      'contact.info.title': 'Get in Touch',
      'contact.avail.label': 'Availability',
      'contact.avail.val': 'Monday – Friday<br>Response within 24 business hours',
      'contact.ethics.title': 'How We Handle Your Information',
      'contact.ethics.text': 'Every contact made to ISSLA Risk is protected under our Code of Ethics and handled with the same discretion we apply to our intelligence work. We do not share client information with third parties, do not disclose inquiry subjects, and do not retain personal data beyond the scope of the engagement.',
      'contact.ethics.link': 'Read Our Code of Ethics →',
      'contact.form.title': 'Send an Inquiry',
      'contact.form.name.label': 'Full Name <span style="color:var(--gold)">*</span>',
      'contact.form.name.ph': 'Your full name',
      'contact.form.org.label': 'Organization <span style="color:var(--gold)">*</span>',
      'contact.form.org.ph': 'Company or firm name',
      'contact.form.email.label': 'Email Address <span style="color:var(--gold)">*</span>',
      'contact.form.service.label': 'Service of Interest',
      'contact.form.opt0': 'Select a service (optional)',
      'contact.form.opt1': 'Enhanced Due Diligence',
      'contact.form.opt2': 'KYC / Customer Due Diligence',
      'contact.form.opt3': 'Reputational Intelligence',
      'contact.form.opt4': 'Jurisdictional Risk Assessment',
      'contact.form.opt5': 'Other / Not sure',
      'contact.form.msg.label': 'Nature of Inquiry',
      'contact.form.msg.ph': 'Briefly describe the nature of your inquiry. All information submitted is treated with strict confidentiality.',
      'contact.form.submit': 'Submit Mandate',
      'contact.form.conf': 'Your inquiry is protected. ISSLA Risk treats all initial contacts with strict confidentiality. No information submitted through this form — including your identity, your organization, and the nature of your inquiry — will be disclosed to any third party or to the subject of a potential engagement. All communications are reviewed exclusively by authorized ISSLA Risk personnel under the terms of our Code of Ethics.',
      'contact.success.title': 'Inquiry Received',
      'contact.success.text': 'A member of our team will contact you within 24 business hours. All information you submitted is protected under our Code of Ethics.',
    },

    es: {
      /* --- NAV --- */
      'nav.services': 'Servicios',
      'nav.about': 'Nosotros',
      'nav.faq': 'Preguntas',
      'nav.contact': 'Contacto',
      'nav.cta': 'Solicitar Sesión',
      /* --- FOOTER --- */
      'footer.tagline': 'Navegando Riesgos Complejos con Inteligencia Accionable',
      'footer.disclaimer1': 'Los servicios de inteligencia prestados no constituyen asesoramiento legal, regulatorio o de cumplimiento.',
      'footer.disclaimer2': 'ISSLA Risk es una firma consultora y asesora de inteligencia corporativa. No operamos como agencia de investigación privada con licencia.',
      'footer.col.services': 'Servicios',
      'footer.link.dd': 'Due Diligence',
      'footer.link.bg': 'Análisis de Antecedentes',
      'footer.link.rep': 'Análisis de Reputación',
      'footer.link.cr': 'Riesgo País',
      'footer.col.company': 'Empresa',
      'footer.link.about': 'Nosotros',
      'footer.link.faq': 'Preguntas',
      'footer.link.contact': 'Contacto',
      'footer.col.follow': 'Síguenos',
      'footer.col.legal': 'Legal',
      'footer.link.privacy': 'Política de Privacidad',
      'footer.link.cookie': 'Política de Cookies',
      'footer.link.terms': 'Términos y Condiciones',
      'footer.link.ethics': 'Código de Ética',
      'footer.copyright': '© 2025 ISSLA Risk Global Services LLC. Todos los derechos reservados.',
      'footer.offices': 'Oficinas: Estados Unidos · Panamá',
      'footer.confidentiality': 'Este sitio y sus contenidos son estrictamente confidenciales.',
      'footer.privacy': 'Política de Privacidad',
      /* --- COOKIE BANNER --- */
      'cookie.text': 'Usamos cookies para mejorar tu experiencia.',
      'cookie.accept': 'Aceptar',
      'cookie.decline': 'Rechazar',
      /* --- INDEX — NUEVO FOCUS EN CONVERSIÓN --- */
      /* Hero */
      'home.hero.eyebrow': 'ISSLA Risk — Inteligencia Corporativa',
      'home.hero.h1': 'Sepa exactamente con quién está haciendo negocios — antes de que sea tarde.',
      'home.hero.sub': 'Informes de inteligencia de fuentes abiertas sobre individuos y empresas en 48\u201372 horas.',
      'home.hero.cta': 'Solicitar informe ahora',
      /* Pilares */
      'home.pillar1.title': 'Qué incluye el informe EDD',
      'home.pillar1.li1': 'Antecedentes completos',
      'home.pillar1.li2': 'Litigios y экспosos legales',
      'home.pillar1.li3': 'Activos identificados',
      'home.pillar1.li4': 'Redes corporativas',
      'home.pillar1.li5': 'Riesgo reputacional',
      'home.pillar2.title': 'Tiempo de entrega',
      'home.pillar2.text': 'Entrega en 48\u201372 horas hábiles desde la confirmación del pago. Formato PDF confidencial con clasificación de riesgo.',
      'home.pillar3.title': 'Confidencialidad garantizada',
      'home.pillar3.text': 'NDA desde el primer contacto. Metodología no atribuible. Sus datos y los del sujeto investigado permanecen protegidos en todo momento.',
      /* Audiencia */
      'home.audience.title': '¿Para quién es esto?',
      'home.audience.lawyers': 'Abogados en litigios',
      'home.audience.lawyers.desc': 'Verifique contrapartes, testigos y partes interesadas antes de estrategias procesales.',
      'home.audience.ma': 'Empresas en due diligence de M&A',
      'home.audience.ma.desc': 'Informes EDD verificados para comités de inversión y procesos de fusión y adquisición.',
      'home.audience.investors': 'Inversores privados',
      'home.audience.investors.desc': 'Conozca a sus potenciales socios de inversión antes de comprometer capital.',
      'home.audience.compliance': 'Compliance officers',
      'home.audience.compliance.desc': 'Cumplimiento AML/KYC con inteligencia verificable y defendible ante reguladores.',
      /* Autoridad */
      'home.authority.title': 'Metodología verificada',
      'home.authority.desc': 'Combinamos tres flujos de inteligencia para cada informe:',
      'home.authority.osint': 'Registros oficiales, archivos judiciales, registros corporativos y fuentes públicas verificadas.',
      'home.authority.humint': 'Redes de fuentes primarias en terreno para confirmación de actividad empresarial y reputación.',
      'home.authority.socmin': 'Análisis de patrones en redes profesionales y comportamiento digital.',
      'home.authority.jurisdictions.title': 'Jurisdicciones cubiertas',
      'home.authority.deliverable.title': 'Formato del entregable',
      'home.authority.deliverable.format': 'Formato',
      'home.authority.deliverable.formatval': 'PDF Confidencial',
      'home.authority.deliverable.classification': 'Clasificación',
      'home.authority.deliverable.classval': 'Nivel de Riesgo',
      'home.authority.deliverable.sources': 'Fuentes',
      'home.authority.deliverable.sourcesval': 'Verificadas y citadas',
      /* Precios */
      'home.pricing.title': 'Informes EDD — Opciones disponibles',
      'home.pricing.sub': 'Cada informe incluye executive summary, hallazgos verificados y clasificación de riesgo.',
      'home.pricing.cta': 'Ordenar este informe',
      'home.pricing.basic.tier': 'Básico',
      'home.pricing.basic.name': 'EDD Standard',
      'home.pricing.basic.desc': 'Registros públicos, antecedentes judiciales, estructura corporativa básica y screening de sanciones.',
      'home.pricing.basic.f1': 'Antecedentes personales',
      'home.pricing.basic.f2': 'Litigios y expedientes',
      'home.pricing.basic.f3': 'Screening AML/KYC',
      'home.pricing.basic.f4': 'Estructura corporativa básica',
      'home.pricing.basic.delivery': 'Entrega: 48\u201372 horas',
      'home.pricing.adv.badge': 'Recomendado',
      'home.pricing.adv.tier': 'Avanzado',
      'home.pricing.adv.name': 'EDD Comprehensive',
      'home.pricing.adv.desc': 'Análisis completo de antecedentes, activos, redes corporativas, fuentes humanas y riesgo reputacional.',
      'home.pricing.adv.f1': 'Todo lo del nivel Básico',
      'home.pricing.adv.f2': 'Activos identificados',
      'home.pricing.adv.f3': 'Redes corporativas completas',
      'home.pricing.adv.f4': 'HUMINT + SOCMIN',
      'home.pricing.adv.f5': 'Análisis de riesgo reputacional',
      'home.pricing.adv.delivery': 'Entrega: 48\u201372 horas',
      'home.pricing.exec.tier': 'Executive',
      'home.pricing.exec.name': 'EDD Executive',
      'home.pricing.exec.desc': 'Informe de máxima profundidad para decisiones críticas. Incluye briefing ejecutivo con analista senior.',
      'home.pricing.exec.f1': 'Todo lo del nivel Advanced',
      'home.pricing.exec.f2': 'Deep dive financiero',
      'home.pricing.exec.f3': 'Briefing con analista senior',
      'home.pricing.exec.f4': 'Seguimiento de 30 días',
      'home.pricing.exec.delivery': 'Entrega: 5\u20137 días hábiles',
      /* Pago */
      'home.payment.title': 'Cómo iniciar tu investigación',
      'home.payment.step1.title': 'Completa el formulario',
      'home.payment.step1.desc': 'Ingresa los datos del sujeto a investigar: nombre, país/jurisdicción y cualquier información adicional relevante.',
      'home.payment.step2.title': 'Realiza la transferencia',
      'home.payment.step2.desc': 'Transfiere al número de cuenta que aparece a continuación. Indica tu nombre como referencia.',
      'home.payment.bank.name': 'Banco',
      'home.payment.bank.account': 'Cuenta',
      'home.payment.bank.routing': 'Routing',
      'home.payment.bank.swift': 'SWIFT',
      'home.payment.reveal': 'Revelar datos bancarios',
      'home.payment.step3.title': 'Recibe tu informe',
      'home.payment.step3.desc': 'Confirmamos tu pago y enviamos el informe EDD en 48\u201372 horas hábiles en formato PDF confidencial.',
      'home.payment.form.name': 'Nombre del solicitante *',
      'home.payment.form.name.ph': 'Tu nombre completo',
      'home.payment.form.email': 'Email *',
      'home.payment.form.email.ph': 'tu@email.com',
      'home.payment.form.subject': 'Nombre del sujeto a investigar *',
      'home.payment.form.subject.ph': 'Nombre completo o razón social',
      'home.payment.form.country': 'País / Jurisdicción *',
      'home.payment.form.country.ph': 'Seleccionar jurisdicción',
      'home.payment.form.tier': 'Tipo de informe',
      'home.payment.form.tierbasic': 'EDD Standard (Básico)',
      'home.payment.form.tieradv': 'EDD Comprehensive (Avanzado)',
      'home.payment.form.tierexec': 'EDD Executive',
      'home.payment.form.message': 'Información adicional (opcional)',
      'home.payment.form.message.ph': 'Cualquier información adicional que pueda ayudar en la investigación...',
      'home.payment.form.submit': 'Enviar solicitud y confirmar pago',
      'home.payment.form.confidential': 'Toda la información proporcionada es estrictamente confidencial y será utilizada únicamente para generar el informe solicitado.',
      'home.payment.success.title': 'Solicitud recibida',
      'home.payment.success.text': 'Nos pondremos en contacto en menos de 24 horas hábiles para confirmar los detalles y proceder con la entrega de su informe.',
      /* --- SERVICES --- */
      'svc.hero.eyebrow': 'Nuestros Servicios',
      'svc.hero.title': 'Inteligencia Corporativa y Due Diligence Reforzado',
      'svc.hero.sub': 'Soluciones expertas para navegar mercados complejos y proteger sus inversiones. Cuatro disciplinas, cada una calibrada a la exposición al riesgo específica de su mandato.',
      'svc.s1.eyebrow': 'Servicio 01',
      'svc.s1.title': 'Due Diligence Reforzado',
      'svc.s1.body1': 'El Due Diligence Global es nuestro servicio más completo, diseñado para transacciones de M&A, empresas conjuntas, relaciones con contrapartes de alto valor y decisiones críticas de contratación. Vamos más allá de las búsquedas en bases de datos para revelar la información que determina si un acuerdo, asociación o nombramiento conlleva riesgos ocultos.',
      'svc.s1.body2': 'Nuestros compromisos de due diligence cubren estructura corporativa y titularidad real, historial financiero y exposición a litigios, sanciones regulatorias y cumplimiento AML/KYC, mapeo de propiedades corporativas e identificación de UBO — entregados en formatos de informe escalonados calibrados a su exposición al riesgo y cronograma de decisión.',
      'svc.s1.included': 'Qué Incluye',
      'svc.s1.li1': 'Estructura corporativa y titularidad real',
      'svc.s1.li2': 'Historial de litigios y exposición legal',
      'svc.s1.li3': 'Escrutinio regulatorio y de sanciones (AML/KYC/OFAC)',
      'svc.s1.li4': 'Análisis de historial financiero',
      'svc.s1.li5': 'Identificación de UBO',
      'svc.s1.li6': 'Cobertura multijurisdiccional',
      'svc.s1.tiers.header': 'Niveles de Informe',
      'svc.s1.tier.basic.key': 'Básico',
      'svc.s1.tier.basic.val': 'Registros básicos, fuentes públicas · 5–10 días',
      'svc.s1.tier.int.key': 'Intermedio',
      'svc.s1.tier.int.val': 'OSINT extendido + consulta de fuentes · 10–18 días',
      'svc.s1.tier.adv.key': 'Avanzado',
      'svc.s1.tier.adv.val': 'HUMINT completo + consulta de fuentes en terreno · 15–25 días',
      'svc.s1.tiers.footer': 'Todos los niveles incluyen resumen ejecutivo + evaluación de riesgos',
      'svc.s1.bestfor': 'Ideal Para',
      'svc.s2.eyebrow': 'Servicio 02',
      'svc.s2.title': 'KYC / Due Diligence de Clientes',
      'svc.s2.body1': 'El Análisis de Antecedentes es un compromiso de inteligencia focalizado diseñado para individuos o entidades específicas donde no se justifica el alcance completo de due diligence. Es el servicio preferido para vetting ejecutivo, nombramientos directivos, evaluaciones de contrataciones clave y screening previo preliminar.',
      'svc.s2.body2': 'Aplicamos metodología de inteligencia de fuentes abiertas para construir un perfil verificado del sujeto — usando registros corporativos, expedientes judiciales, archivos de medios, redes profesionales y bases de datos sectoriales — e identificamos señales de alerta que la revisión convencional de RRHH o legal no detectaría.',
      'svc.s2.included': 'Qué Incluye',
      'svc.s2.li1': 'Mapeo de registro corporativo y directorado',
      'svc.s2.li2': 'Registros judiciales e historial de litigios',
      'svc.s2.li3': 'Revisión de archivo de medios e identificación de alertas',
      'svc.s2.li4': 'Análisis de red profesional y asociaciones',
      'svc.s2.li5': 'Escrutinio de bases de datos sectoriales',
      'svc.s2.li6': 'Evaluación de riesgos resumida con calificaciones de confianza',
      'svc.s2.bestfor': 'Ideal Para',
      'svc.s2.eng.header': 'Detalles del Compromiso',
      'svc.s2.eng.deliv.key': 'Entrega',
      'svc.s2.eng.deliv.val': '5–10 días hábiles',
      'svc.s2.eng.lang.key': 'Idiomas',
      'svc.s2.eng.lang.val': 'Inglés y Español',
      'svc.s2.eng.scope.key': 'Alcance',
      'svc.s2.eng.scope.val': 'Individuo o entidad',
      'svc.s2.eng.footer': 'Disponible de forma independiente o como pre-calificación para due diligence completo',
      'svc.s3.eyebrow': 'Servicio 03',
      'svc.s3.title': 'Inteligencia Reputacional',
      'svc.s3.body1': 'El Análisis de Reputación es un producto de inteligencia enfocado en la narrativa pública y no pública que rodea a una persona, entidad o marca. Está diseñado para clientes que necesitan comprender cómo es percibido un sujeto — en medios, redes profesionales, canales sectoriales y entornos de fuentes abiertas — antes de establecer una relación.',
      'svc.s3.body2': 'Identificamos vectores de riesgo reputacional: patrones de medios adversos, asociaciones polémicas, riesgos a nivel de red y discrepancias entre el perfil declarado y el observado. El entregable es una evaluación de riesgos calibrada, no un resumen de medios.',
      'svc.s3.included': 'Qué Incluye',
      'svc.s3.li1': 'Identificación de patrones en medios adversos',
      'svc.s3.li2': 'Mapeo de riesgos por controversia y asociación',
      'svc.s3.li3': 'Análisis de discrepancias entre perfil declarado y observado',
      'svc.s3.li4': 'Evaluación de exposición a nivel de red',
      'svc.s3.li5': 'Revisión de huella digital y en redes sociales',
      'svc.s3.li6': 'Calificación de riesgo calibrada con hallazgos documentados',
      'svc.s3.what.header': 'Qué Revela',
      'svc.s3.adv.key': 'Medios Adversos',
      'svc.s3.adv.val': 'Basado en patrones, no en palabras clave',
      'svc.s3.cont.key': 'Controversias',
      'svc.s3.cont.val': 'Asociaciones históricas y emergentes',
      'svc.s3.disc.key': 'Discrepancias',
      'svc.s3.disc.val': 'Brechas entre perfil declarado y observado',
      'svc.s3.net.key': 'Riesgo de Red',
      'svc.s3.net.val': 'Exposiciones indirectas vía asociaciones',
      'svc.s3.dig.key': 'Huella Digital',
      'svc.s3.dig.val': 'Mapeo de presencia online y señales',
      'svc.s3.footer': 'Entregable: evaluación de riesgos calibrada con documentación de fuentes',
      'svc.s3.bestfor': 'Ideal Para',
      'svc.s4.eyebrow': 'Servicio 04',
      'svc.s4.title': 'Evaluación de Riesgo Jurisdiccional',
      'svc.s4.body1': 'Nuestras evaluaciones de Riesgo País entregan un análisis estructurado del entorno político, regulatorio, de seguridad y operacional en una jurisdicción objetivo. Están diseñadas para organizaciones que planifican entrada a mercados, estrategias de protección de activos o continuidad operacional en entornos complejos o de alto riesgo.',
      'svc.s4.body2': 'La cobertura es más profunda en América Latina, el Caribe y el Medio Oriente — mercados donde la volatilidad política, la opacidad regulatoria y los factores ESG crean riesgos que la investigación de mercado estándar no capta.',
      'svc.s4.included': 'Qué Incluye',
      'svc.s4.li1': 'Marco de calificación de riesgos por dominio',
      'svc.s4.li2': 'Análisis de escenarios políticos y pronósticos',
      'svc.s4.li3': 'Visión general regulatoria y de cumplimiento',
      'svc.s4.li4': 'Factores de riesgo ESG y mapeo de exposición',
      'svc.s4.li5': 'Evaluación del entorno de seguridad',
      'svc.s4.li6': 'Recomendaciones operacionales',
      'svc.s4.deliv.header': 'Entregables',
      'svc.s4.risk.key': 'Marco de Riesgo',
      'svc.s4.risk.val': 'Matriz de calificación de riesgos multidominio',
      'svc.s4.pol.key': 'Político',
      'svc.s4.pol.val': 'Análisis de escenarios y pronóstico de probabilidad',
      'svc.s4.reg.key': 'Regulatorio',
      'svc.s4.reg.val': 'Panorama de cumplimiento normativo',
      'svc.s4.esg.key': 'ESG',
      'svc.s4.esg.val': 'Factores de riesgo ambiental, social y de gobernanza',
      'svc.s4.op.key': 'Operacional',
      'svc.s4.op.val': 'Recomendaciones accionables por escenario',
      'svc.s4.footer': 'Los compromisos incluyen una llamada de briefing ejecutivo al momento de la entrega',
      'svc.s4.coverage': 'Cobertura',
      'svc.rep.eyebrow': 'Entregables',
      'svc.rep.title': 'Inteligencia Defendible. Entrega Decisiva.',
      'svc.rep.sub': 'Todos los informes comienzan con un resumen ejecutivo y evaluación de riesgos, seguidos de hallazgos detallados organizados por dominio de inteligencia.',
      'svc.rep.basic.num': 'Básico',
      'svc.rep.basic.name': 'Informe de Base',
      'svc.rep.basic.desc': 'Registros básicos y hallazgos de fuentes públicas. Resumen ejecutivo, alertas de riesgo clave, calificaciones de confianza. Entrega en 5–10 días hábiles.',
      'svc.rep.int.num': 'Intermedio',
      'svc.rep.int.name': 'Informe Estándar',
      'svc.rep.int.desc': 'OSINT extendido más consulta de fuentes. Hallazgos completos por dominio con atribución de fuentes. Entrega en 10–18 días hábiles.',
      'svc.rep.adv.num': 'Avanzado',
      'svc.rep.adv.name': 'Informe de Inteligencia Completo',
      'svc.rep.adv.desc': 'HUMINT completo y consulta de fuentes en terreno. Análisis exhaustivo por dominio con toda la documentación de confianza y fuentes. 15–25 días hábiles.',
      'svc.rep.sample': 'Se dispone de un informe de muestra redactado a solicitud · info@isslarisk.com',
      'svc.cta.title': 'Inicie su Due Diligence',
      'svc.cta.sub': 'Describa su consulta y en 48 horas le indicaremos el servicio adecuado.',
      'svc.cta.btn': 'Enviar un Mandato',
      'svc.included.label': 'Qué Incluye',
      'svc.bestfor.label': 'Ideal Para',
      'svc.s1.bullets': '<li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Estructura corporativa y propiedad efectiva</li>\n            <li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Historial de litigios y exposición legal</li>\n            <li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Verificación regulatoria y de sanciones (AML/KYC/OFAC)</li>\n            <li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Análisis de antecedentes financieros</li>\n            <li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Identificación de UBO</li>\n            <li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Cobertura multijurisdiccional</li>',
      'svc.s2.bullets': '<li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Mapeo de registros corporativos y directorios</li>\n            <li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Expedientes judiciales e historial de litigios</li>\n            <li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Revisión de archivos de medios e identificación de señales adversas</li>\n            <li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Análisis de redes profesionales y asociaciones</li>\n            <li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Screening en bases de datos sectoriales</li>\n            <li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Evaluación de riesgo resumida con calificaciones de confianza</li>',
      'svc.s3.bullets': '<li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Identificación de patrones en medios adversos</li>\n            <li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Mapeo de riesgo por controversias y asociaciones</li>\n            <li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Análisis de discrepancias entre perfil declarado y observado</li>\n            <li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Evaluación de exposición a nivel de red</li>\n            <li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Revisión de huella digital y en redes sociales</li>\n            <li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Calificación de riesgo calibrada con hallazgos documentados</li>',
      'svc.s4.bullets': '<li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Marco de calificación de riesgos por dominio</li>\n            <li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Análisis de escenarios políticos y proyecciones</li>\n            <li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Panorama regulatorio y de cumplimiento normativo</li>\n            <li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Mapeo de factores de riesgo ESG y exposición</li>\n            <li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Evaluación del entorno de seguridad</li>\n            <li style="font-size:14px; color:var(--text-secondary); padding-left:18px; position:relative;"><span style="position:absolute; left:0; color:var(--gold); opacity:0.7;">—</span> Recomendaciones operacionales</li>',
      /* --- ABOUT --- */
      'about.hero.eyebrow': 'Sobre la Firma',
      'about.hero.title': 'Due Diligence Estratégico · Inteligencia en Transacciones · Riesgo Transfronterizo',
      'about.hero.sub': '17 años. Más de 1.200 mandatos. Cobertura en terreno donde otros dependen de bases de datos. Inteligencia antes del despliegue de capital.',
      'about.who.eyebrow': 'Quiénes Somos',
      'about.who.title': 'Inteligencia Corporativa para Decisiones de Alto Impacto',
      'about.who.body1': 'ISSLA Risk es una firma especializada en inteligencia corporativa y asesoría de riesgos. Servimos a corporaciones multinacionales, fondos de capital privado, despachos jurídicos, family offices y entidades gubernamentales que requieren inteligencia verificada antes de comprometer capital, establecer asociaciones o expandirse hacia mercados complejos.',
      'about.who.body2': 'Nuestros analistas combinan inteligencia de fuentes abiertas, redes de fuentes humanas y metodologías de investigación propietarias para producir informes que no son meramente informativos — son accionables. Cada compromiso se trata con absoluta discreción, y cada hallazgo está documentado, verificado y presentado profesionalmente.',
      'about.who.body3': 'Operamos en las Américas, Europa, el Medio Oriente y el Norte de África, con profundidad especializada en mercados latinoamericanos y del Caribe que nos diferencia de las consultoras generalistas.',
      'about.stat.engagements': 'Mandatos Completados',
      'about.stat.countries': 'Países Cubiertos',
      'about.stat.confidential': 'Años de Operación',
      'about.dossier.header': 'PERFIL DE LA FIRMA',
      'about.dossier.confidential': 'CONFIDENCIAL',
      'about.dossier.founded.key': 'Fundada',
      'about.dossier.entity.key': 'Entidad',
      'about.dossier.category.key': 'Categoría',
      'about.dossier.hq.key': 'Sede Principal',
      'about.dossier.regional.key': 'Oficina Regional',
      'about.dossier.coverage.key': 'Cobertura',
      'about.dossier.coverage.val': 'Norteamérica · Caribe · Sudamérica',
      'about.dossier.languages.key': 'Idiomas',
      'about.dossier.mandate.key': 'Mandato',
      'about.dossier.mandate.val': 'Inteligencia verificada. Tolerancia cero a afirmaciones no verificadas.',
      'about.dossier.ethics.key': 'Ética',
      'about.dossier.ethics.val': 'Cumplimiento total con GDPR y Ley de Privacidad',
      'about.method.eyebrow': 'Cómo Trabajamos',
      'about.method.title': 'Una Metodología Construida sobre la Verificación',
      'about.method.sub': 'Cada compromiso de ISSLA Risk sigue un ciclo de inteligencia estructurado de tres fases — garantizando que cada conclusión en su informe pueda resistir el escrutinio profesional.',
      'about.method.1.name': 'OSINT — Inteligencia de Fuentes Abiertas',
      'about.method.1.tag': 'Capa de Inteligencia 01',
      'about.method.1.desc': 'Comenzamos con un barrido estructurado de fuentes abiertas: registros corporativos, expedientes judiciales, presentaciones regulatorias, bases de datos de sanciones, archivos de medios adversos y fuentes gubernamentales oficiales. Esta fase construye la capa de datos fundamental para cada compromiso y establece una línea de tiempo base de las actividades del sujeto.',
      'about.method.2.name': 'HUMINT — Inteligencia Humana',
      'about.method.2.tag': 'Capa de Inteligencia 02',
      'about.method.2.desc': 'Donde terminan los documentos, comienzan las personas. Nuestras redes de fuentes regionales proveen verificación a nivel de terreno que ninguna base de datos puede replicar: confirmación de actividad comercial, reputación entre pares, patrones de conducta y relaciones que los registros formales nunca capturan. Todo el HUMINT es gestionado bajo estrictos protocolos de seguridad operacional.',
      'about.method.3.name': 'SOCMIN — Inteligencia en Redes Sociales',
      'about.method.3.tag': 'Capa de Inteligencia 03',
      'about.method.3.desc': 'Las huellas digitales revelan lo que las fuentes formales ocultan. Los analistas de ISSLA Risk realizan análisis estructurado de perfiles profesionales y en redes sociales, declaraciones públicas, afiliaciones de red y patrones de conducta en línea. Esta capa es especialmente valiosa para identificar inconsistencias entre posiciones declaradas y conducta observada.',
      'about.cap.eyebrow': 'Capacidades Principales',
      'about.cap.title': 'Lo Que Diferencia a ISSLA Risk',
      'about.cap.1.title': 'Profundidad Regional',
      'about.cap.1.desc': 'Expertise especializado en mercados latinoamericanos y del Caribe — jurisdicciones donde las redes informales, la dinámica política y la opacidad de los registros exigen analistas con conocimiento genuino en terreno, no solo acceso a bases de datos.',
      'about.cap.2.title': 'Verificación Multicapa',
      'about.cap.2.desc': 'Ningún hallazgo llega a su informe sin corroboración independiente. Cada afirmación significativa se verifica en al menos dos fuentes independientes — eliminando el problema del rumor como hecho que afecta a productos de inteligencia de menor calidad.',
      'about.cap.3.title': 'Integración Legal y de Cumplimiento',
      'about.cap.3.desc': 'Nuestros analistas comprenden cómo se utilizarán los informes — en presentaciones ante comités de inversión, procedimientos legales, presentaciones regulatorias y decisiones directivas. Los informes están estructurados para cumplir con los estándares probatorios de su caso de uso específico.',
      'about.cap.4.title': 'Discreción Absoluta',
      'about.cap.4.desc': 'Cada compromiso es confidencial por defecto. No confirmamos ni negamos relaciones con clientes, no usamos información del cliente para ningún propósito más allá del compromiso específico, y todos los entregables se transmiten a través de canales seguros.',
      'about.sectors.eyebrow': 'Industrias Atendidas',
      'about.sectors.title': 'Confianza en Múltiples Sectores',
      'about.sectors.sub': 'Cualquier organización cuyas decisiones conlleven consecuencias financieras, legales o reputacionales significativas se beneficia de la inteligencia verificada.',
      'about.sector.pe': 'Capital Privado y Capital de Riesgo',
      'about.sector.corp': 'Corporaciones Multinacionales',
      'about.sector.legal': 'Despachos Jurídicos',
      'about.sector.fo': 'Family Offices',
      'about.sector.fi': 'Instituciones Financieras',
      'about.sector.ins': 'Seguros y Reaseguros',
      'about.sector.re': 'Bienes Raíces y Desarrollo',
      'about.sector.gov': 'Entidades Gubernamentales',
      'about.sector.energy': 'Energía y Recursos Naturales',
      'about.sector.pharma': 'Farmacéutica y Salud',
      'about.sector.infra': 'Infraestructura y Construcción',
      'about.sector.tech': 'Tecnología y Telecomunicaciones',
      'about.cov.eyebrow': 'Cobertura Geográfica',
      'about.cov.title': 'Dónde Operamos',
      'about.cov.sub': 'ISSLA Risk cubre Norteamérica, el Caribe y Sudamérica — con profundidad especializada en los mercados donde la opacidad, el riesgo político y la complejidad jurisdiccional son más altos.',
      'about.cov.na.title': 'Norteamérica',
      'about.cov.na.desc': 'Cobertura completa de Estados Unidos y Canadá, incluyendo análisis corporativos transfronterizos, investigación de cumplimiento regulatorio y vetting de socios previo a transacciones en todas las principales jurisdicciones.',
      'about.cov.carib.title': 'El Caribe',
      'about.cov.carib.desc': 'Profundidad especializada en jurisdicciones offshore del Caribe, registros corporativos de estados insulares y centros financieros regionales — donde la opacidad de titularidad real y la complejidad de estructuras societarias exigen conocimiento local experimentado.',
      'about.cov.sa.title': 'Sudamérica',
      'about.cov.sa.desc': 'Cobertura integral de los mercados sudamericanos, con expertise particular en Colombia, Brasil, Argentina y Perú — jurisdicciones con alta actividad de inversión junto con elevado riesgo político y regulatorio.',
      'about.off.eyebrow': 'Nuestras Oficinas',
      'about.off.title': 'Dos Ubicaciones Estratégicas',
      'about.off.1.flag': 'Américas — Sede Principal',
      'about.off.1.hours': 'Lun – Vie, 09:00 – 18:00 GMT-3',
      'about.off.2.flag': 'América Latina — Oficina Regional',
      'about.off.2.hours': 'Lun – Vie, 09:00 – 17:00 GMT-3',
      'about.off.2.ops': 'Operaciones de inteligencia en América Latina y el Caribe',
      'about.cta.title': 'Inicie su Due Diligence',
      'about.cta.sub': 'Contacte a nuestro equipo para discutir sus requisitos específicos de inteligencia. Todas las consultas se tratan con absoluta confidencialidad.',
      'about.cta.btn1': 'Solicitar una Sesión',
      'about.cta.btn2': 'Ver Nuestros Servicios',
      /* --- FAQ --- */
      'faq.hero.eyebrow': 'Preguntas Frecuentes',
      'faq.hero.title': 'Preguntas y Respuestas',
      'faq.hero.sub': 'Todo lo que necesita saber sobre los servicios, el proceso y el modo de trabajo de ISSLA Risk. Si su pregunta no tiene respuesta aquí, contáctenos directamente.',
      'faq.cat.about': 'Sobre ISSLA Risk',
      'faq.cat.services': 'Nuestros Servicios',
      'faq.cat.process': 'Proceso y Metodología',
      'faq.cat.confidentiality': 'Confidencialidad y Seguridad',
      'faq.cat.reports': 'Informes y Entregables',
      'faq.cat.engagement': 'Iniciar un Compromiso',
      'faq.sidebar.still': '¿Aún tiene preguntas?',
      'faq.sidebar.contact': 'Contáctenos',
      'faq.a1.q': '¿Qué es ISSLA Risk?',
      'faq.a1.a': '<p>ISSLA Risk es una firma especializada en inteligencia corporativa y asesoría de riesgos. Proveemos productos de inteligencia verificada a corporaciones multinacionales, fondos de capital privado, despachos jurídicos, family offices y entidades gubernamentales. Nuestro trabajo se enfoca en cuatro disciplinas: due diligence global, análisis de antecedentes, análisis de reputación y riesgo país y pronóstico político.</p>',
      'faq.a2.q': '¿Dónde está ubicada ISSLA Risk?',
      'faq.a2.a': '<p>Nuestra sede principal está en Albuquerque, Nuevo México, EE.UU. También operamos una oficina regional en Ciudad de Panamá, República de Panamá, que apoya nuestras operaciones de inteligencia en América Latina y el Caribe. Ambas oficinas pueden contactarse en info@isslarisk.com.</p>',
      'faq.a3.q': '¿Qué regiones geográficas cubre ISSLA Risk?',
      'faq.a3.a': '<p>ISSLA Risk cubre Norteamérica, el Caribe y Sudamérica. Tenemos expertise particular en mercados con alta opacidad, riesgo político o entornos regulatorios complejos — incluyendo Estados Unidos, Canadá, Panamá, Colombia, Brasil, Argentina, Perú, México y jurisdicciones offshore del Caribe como BVI e Islas Caimán. Fundada en 2009, hemos construido redes de fuentes especializadas en estas regiones a lo largo de más de quince años de actividad operacional.</p>',
      'faq.s1.q': '¿Qué servicios ofrece ISSLA Risk?',
      'faq.s1.a': '<p>Ofrecemos cuatro servicios principales de inteligencia:</p><ul><li><strong>Due Diligence Global</strong> — Vetting previo a inversión, socios y proveedores, disponible en tres niveles (Básico, Completo y Ejecutivo).</li><li><strong>Análisis de Antecedentes</strong> — Investigación profunda de historial profesional y registros públicos sobre individuos para nombramientos o asociaciones de alto impacto.</li><li><strong>Análisis de Reputación</strong> — Evaluación estructurada de cómo es percibida una entidad o individuo en mercados, medios y redes de partes interesadas.</li><li><strong>Riesgo País y Pronóstico Político</strong> — Evaluaciones de riesgo geopolítico y regulatorio para entrada a mercados, decisiones operacionales o comités de inversión.</li></ul>',
      'faq.s2.q': '¿Quiénes son sus clientes típicos?',
      'faq.s2.a': '<p>Nuestros clientes incluyen corporaciones multinacionales, fondos de capital privado y capital de riesgo, despachos jurídicos, family offices, instituciones financieras, compañías de seguros y reaseguros, promotores inmobiliarios, empresas energéticas y entidades gubernamentales. El hilo conductor es que toman decisiones con consecuencias financieras, legales o reputacionales significativas — y requieren inteligencia verificada, no especulación.</p>',
      'faq.s3.q': '¿Puede ISSLA Risk realizar análisis de antecedentes sobre individuos?',
      'faq.s3.a': '<p>Sí — el análisis de antecedentes sobre individuos es uno de nuestros servicios principales, realizado como investigación de fuentes abiertas y registros públicos dentro del alcance de nuestro mandato como firma consultora de inteligencia corporativa. Toda investigación se realiza mediante métodos legales: registros públicos, expedientes judiciales, archivos de medios, redes profesionales y consulta de fuentes humanas. Investigamos historial profesional, situación regulatoria, registros de litigios, conducta financiera y perfil reputacional. ISSLA Risk es una firma consultora y asesora de inteligencia corporativa — no operamos como agencia de investigación privada con licencia, y no realizamos vigilancia, seguimiento físico encubierto ni ninguna actividad fuera de los límites de la ley aplicable.</p>',
      'faq.p1.q': '¿Qué metodología utiliza ISSLA Risk?',
      'faq.p1.a': '<p>Nuestra metodología se basa en tres capas de inteligencia: OSINT (Inteligencia de Fuentes Abiertas), HUMINT (Inteligencia Humana) y SOCMIN (Inteligencia en Redes Sociales). El OSINT abarca la investigación estructurada de registros públicos, registros, presentaciones y archivos de medios. El HUMINT involucra nuestras redes de fuentes regionales que proveen verificación en terreno. El SOCMIN analiza huellas digitales, perfiles profesionales y patrones de conducta en línea. Cada hallazgo significativo requiere corroboración independiente antes de aparecer en su informe.</p>',
      'faq.p2.q': '¿Cuánto tiempo tarda un compromiso?',
      'faq.p2.a': '<p>El plazo depende del alcance y tipo de compromiso. Un informe de due diligence básico típicamente se entrega en 5–7 días hábiles. Los informes completos generalmente requieren 10–15 días hábiles. Los mandatos ejecutivos, compromisos con múltiples sujetos y evaluaciones de riesgo país se definen individualmente. Podemos discutir entrega acelerada para situaciones urgentes — contáctenos para hablar sobre su cronograma.</p>',
      'faq.p3.q': '¿Cómo verifica ISSLA Risk sus hallazgos?',
      'faq.p3.a': '<p>Ningún hallazgo llega a su informe sin corroboración independiente. Aplicamos un estándar mínimo de dos fuentes para cada afirmación significativa — lo que significa que cada conclusión sustantiva se verifica a través de al menos dos fuentes independientes y no derivadas. Cuando una afirmación no puede verificarse independientemente, se excluye o se etiqueta claramente como no verificada y atribuida a su única fuente. Este estándar no es negociable en ningún nivel de compromiso.</p>',
      'faq.c1.q': '¿Cómo protege ISSLA Risk la confidencialidad del cliente?',
      'faq.c1.a': '<p>La confidencialidad del cliente es el fundamento de nuestra práctica. No confirmamos ni negamos la existencia de ninguna relación con clientes. Todos los detalles, entregables y comunicaciones del compromiso se tratan como estrictamente confidenciales. No usamos información del cliente para ningún propósito secundario, no discutimos mandatos con terceros y no hacemos referencia a clientes anteriores sin autorización escrita explícita. Todo el personal opera bajo acuerdos de confidencialidad vinculantes.</p>',
      'faq.c2.q': '¿Cumple ISSLA Risk con el GDPR y las leyes de protección de datos?',
      'faq.c2.a': '<p>Sí. ISSLA Risk opera en pleno cumplimiento con el Reglamento General de Protección de Datos (GDPR) europeo, la Ley de Privacidad de los Estados Unidos y las regulaciones de protección de datos locales aplicables en cada jurisdicción donde operamos. Toda investigación se realiza sobre bases legales, y los datos personales se procesan estrictamente para el propósito del compromiso específico. Para más detalles, consulte nuestra <a href="privacy-policy.html">Política de Privacidad</a>.</p>',
      'faq.c3.q': '¿Cómo se transmiten los informes y las comunicaciones?',
      'faq.c3.a': '<p>Todos los entregables se transmiten a través de canales seguros y cifrados. No transmitimos informes sensibles por correo electrónico sin cifrar como práctica estándar. Los acuerdos de entrega segura se confirman con cada cliente al inicio del compromiso. Si dispone de protocolos de comunicación segura existentes que prefiere, podemos adaptarnos a ellos.</p>',
      'faq.r1.q': '¿Qué contiene un informe de ISSLA Risk?',
      'faq.r1.a': '<p>La estructura varía según el tipo y nivel de servicio, pero todos los informes incluyen: un resumen ejecutivo para los responsables de la toma de decisiones, hallazgos detallados por categoría de riesgo, atribución de fuentes para cada afirmación sustantiva, una calificación de riesgo o conclusión de evaluación, y recomendaciones accionables. Los informes están formateados profesionalmente y diseñados para ser presentados directamente ante comités de inversión, asesores legales o juntas directivas sin modificación editorial.</p>',
      'faq.r2.q': '¿Cuáles son las diferencias entre los niveles Básico, Completo y Ejecutivo?',
      'faq.r2.a': '<p><strong>Básico:</strong> Cubre escrutinio de sanciones y listas de vigilancia, revisión de medios adversos, verificación de registro corporativo, registros de litigios y resumen preliminar de riesgo. Adecuado para screening inicial. Entrega: 5–7 días hábiles.</p><p><strong>Completo:</strong> Incluye verificación de historial profesional, análisis de conducta financiera, inteligencia reputacional de fuentes humanas, mapeo de red y narrativa de riesgo detallada. Adecuado para mandatos pre-inversión o pre-nombramiento. Entrega: 10–15 días hábiles.</p><p><strong>Ejecutivo:</strong> Compromiso de espectro completo con todos los elementos del nivel Completo más historial financiero profundo, rastreo de titularidad real, despliegue extendido de HUMINT, análisis de estrategia de litigios y sesión de briefing con analista senior. Alcance y cronograma personalizados.</p>',
      'faq.r3.q': '¿Puede ISSLA Risk proporcionar monitoreo continuo en lugar de un informe único?',
      'faq.r3.a': '<p>Sí. Para clientes que requieren visibilidad continua sobre un sujeto, jurisdicción o mercado, ofrecemos acuerdos de monitoreo basados en retainer. Estos se estructuran individualmente según el alcance del monitoreo requerido. Contáctenos para discutir sus requisitos de monitoreo continuo.</p>',
      'faq.e1.q': '¿Cómo inicio un compromiso con ISSLA Risk?',
      'faq.e1.a': '<p>La forma más sencilla de comenzar es a través de nuestro <a href="contact.html">formulario de contacto</a> o enviando un correo a info@isslarisk.com. Responderemos dentro de un día hábil para programar una llamada de briefing confidencial. Durante esa llamada, definimos el alcance, el cronograma, los entregables y los términos comerciales. No se requieren detalles sensibles sobre el sujeto del análisis en la etapa de consulta — solo necesitamos comprender la naturaleza general del mandato para una evaluación inicial.</p>',
      'faq.e2.q': '¿Qué información necesito proporcionar para comenzar?',
      'faq.e2.a': '<p>Al inicio de un compromiso, necesitamos: la identidad del sujeto (individuo o entidad), la(s) jurisdicción(es) de interés principal, el propósito del compromiso (inversión, cumplimiento, apoyo a litigios, etc.) y cualquier preocupación de riesgo específica que desee priorizar. Cuanto más contexto proporcione, mejor podremos adaptar el análisis. Los documentos complementarios — presentaciones corporativas, informes anteriores, correspondencia — son siempre bienvenidos y tratados como estrictamente confidenciales.</p>',
      'faq.e3.q': '¿ISSLA Risk trabaja con clientes fuera de los Estados Unidos?',
      'faq.e3.a': '<p>Absolutamente. ISSLA Risk atiende clientes globalmente independientemente de dónde tengan su sede. Nuestra oficina en Ciudad de Panamá apoya a clientes latinoamericanos y del Caribe, mientras que nuestra sede en Albuquerque atiende mandatos norteamericanos. Trabajamos con organizaciones de todo el mundo que necesitan cobertura de inteligencia dentro de nuestras regiones de operación. Los compromisos se realizan en inglés, español y portugués, y los entregables pueden proporcionarse en el idioma preferido del cliente.</p>',
      'faq.cta.title': '¿No Encontró Su Respuesta?',
      'faq.cta.sub': 'Contacte a nuestro equipo directamente. Todas las consultas se tratan con total confidencialidad y se responden dentro de un día hábil.',
      'faq.cta.btn1': 'Contáctenos',
      'faq.cta.btn2': 'Ver Nuestros Servicios',
      /* --- CONTACT --- */
      'contact.hero.eyebrow': 'Iniciar un Compromiso',
      'contact.hero.title': 'Solicite una Consulta Confidencial',
      'contact.hero.sub': 'Todos los compromisos se realizan bajo nuestro Código de Ética publicado. Las primeras conversaciones son siempre confidenciales — sin compromiso requerido.',
      'contact.info.title': 'Póngase en Contacto',
      'contact.avail.label': 'Disponibilidad',
      'contact.avail.val': 'Lunes – Viernes<br>Respuesta en 24 horas hábiles',
      'contact.ethics.title': 'Cómo Manejamos Su Información',
      'contact.ethics.text': 'Todo contacto realizado con ISSLA Risk está protegido bajo nuestro Código de Ética y se maneja con la misma discreción que aplicamos a nuestro trabajo de inteligencia. No compartimos información de clientes con terceros, no divulgamos los sujetos de consulta y no retenemos datos personales más allá del alcance del compromiso.',
      'contact.ethics.link': 'Leer Nuestro Código de Ética →',
      'contact.form.title': 'Enviar una Consulta',
      'contact.form.name.label': 'Nombre Completo <span style="color:var(--gold)">*</span>',
      'contact.form.name.ph': 'Su nombre completo',
      'contact.form.org.label': 'Organización <span style="color:var(--gold)">*</span>',
      'contact.form.org.ph': 'Nombre de la empresa o firma',
      'contact.form.email.label': 'Correo Electrónico <span style="color:var(--gold)">*</span>',
      'contact.form.service.label': 'Servicio de Interés',
      'contact.form.opt0': 'Seleccione un servicio (opcional)',
      'contact.form.opt1': 'Due Diligence Reforzado',
      'contact.form.opt2': 'KYC / Due Diligence de Clientes',
      'contact.form.opt3': 'Inteligencia Reputacional',
      'contact.form.opt4': 'Evaluación de Riesgo Jurisdiccional',
      'contact.form.opt5': 'Otro / No estoy seguro',
      'contact.form.msg.label': 'Naturaleza de la Consulta',
      'contact.form.msg.ph': 'Describa brevemente la naturaleza de su consulta. Toda la información enviada se trata con estricta confidencialidad.',
      'contact.form.submit': 'Enviar Mandato',
      'contact.form.conf': 'Su consulta está protegida. ISSLA Risk trata todos los contactos iniciales con estricta confidencialidad. Ninguna información enviada a través de este formulario — incluyendo su identidad, su organización y la naturaleza de su consulta — será divulgada a terceros ni al sujeto de un posible compromiso. Todas las comunicaciones son revisadas exclusivamente por personal autorizado de ISSLA Risk bajo los términos de nuestro Código de Ética.',
      'contact.success.title': 'Consulta Recibida',
      'contact.success.text': 'Un miembro de nuestro equipo se pondrá en contacto con usted en 24 horas hábiles. Toda la información que envió está protegida bajo nuestro Código de Ética.',
    }
  };

  /* ----------------------------------------------------------
     ENGINE
  ---------------------------------------------------------- */
  function applyLang(lang) {
    var t = T[lang] || T.en;

    /* textContent nodes */
    document.querySelectorAll('[data-i18n]').forEach(function (el) {
      var key = el.getAttribute('data-i18n');
      if (t[key] !== undefined) el.textContent = t[key];
    });

    /* innerHTML nodes (paragraphs with HTML, FAQ answers) */
    document.querySelectorAll('[data-i18n-html]').forEach(function (el) {
      var key = el.getAttribute('data-i18n-html');
      if (t[key] !== undefined) el.innerHTML = t[key];
    });

    /* placeholder attributes */
    document.querySelectorAll('[data-i18n-ph]').forEach(function (el) {
      var key = el.getAttribute('data-i18n-ph');
      if (t[key] !== undefined) el.placeholder = t[key];
    });

    /* Toggle button active state */
    document.querySelectorAll('.lang-btn').forEach(function (btn) {
      btn.classList.toggle('active', btn.getAttribute('data-lang') === lang);
    });

    /* html[lang] attribute */
    document.documentElement.lang = lang === 'es' ? 'es' : 'en';

    /* Persist */
    try { localStorage.setItem('issla-lang', lang); } catch (e) {}
  }

  function initLang() {
    var saved = 'en';
    try { saved = localStorage.getItem('issla-lang') || 'en'; } catch (e) {}
    applyLang(saved);

    document.querySelectorAll('.lang-btn').forEach(function (btn) {
      btn.addEventListener('click', function () {
        applyLang(btn.getAttribute('data-lang'));
      });
    });
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', initLang);
  } else {
    initLang();
  }

  /* Public API */
  window.ISSLALang = { apply: applyLang };

})();
